version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend folder
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend  # Path to the backend folder
    ports:
      - "5000:5000"
    depends_on:
      - frontend
